# Configurações do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:tmaodb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Flyway vai rodar antes do Hibernate validar o banco
spring.flyway.enabled=true